FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o wordofwisdom-client ./cmd/client/main.go

FROM scratch
COPY --from=builder /app/wordofwisdom-client /wordofwisdom-client
ENTRYPOINT ["/wordofwisdom-client"]
