FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o wordofwisdom ./cmd/server/main.go

FROM scratch
COPY --from=builder /app/wordofwisdom /wordofwisdom
EXPOSE 9000
ENTRYPOINT ["/wordofwisdom"]
