version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9000:9000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
